### ISSUE TITLE
委托单行实验前参数不需要可改，应由前面各项带出，同时注意前面各项变化时要及时刷新实验前参数并带出孙表数据

### ISSUE THREAD

**Issue by sunshaoxuan** [sunshaoxuan/LimsWeb#26]
參考腳本
`_--应用时获取语句(选择样品自动筛选)_

SELECT * from NC_TEST_INIT p
   where p.nc_enstard = 'QFVF4039-2016'
     and p.nc_sample_point = '005D-镀金触点'
   AND ' ' || p.Nc_contact_type || ',' like '% 1Z,%'
   and ' ' || p.NC_COIL_TYPE || ',' like '% 单稳态,%'
   and p.nc_coil_current = '单稳态'
   and p.nc_stage = '常温'
  ORDER BY p.def1
`

**Comment by zly199** [comment]
唯一确认实验前参数的sql语句待确认
