### ISSUE TITLE
委托单表体孙表自定义添加参数项，参照选择参数项之后，系统变得非常卡顿，是否是因为数据量大的问题，是否可以进行优化（顾问提交）

### ISSUE THREAD

**Issue by sunshaoxuan** [sunshaoxuan/LimsWeb#98]

**Comment by zly199** [comment]
1.NC_TEST_INIT可能存在重复数据,请先drop再插入数据
2.孙表参数项没有进行过滤,数据量过大,需要提供过滤条件

**Comment by zly199** [comment]
参考nc.bs.pubapp.utils.UserDefineRefUtils.refreshItemRefValue(SuperVO, UITable, int, BillItem, boolean),已为任务单孙表设置了一个简单的缓存

**Comment by zly199** [comment]
使用2Q缓存暂存了孙表参数项
